server:
  port: 8080
  servlet:
    context-path: /itp

spring:
  profile: DEV
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
ambiente:
  teste: fefeetwet




